version: '3'

services:
  mysql:
    # image: mysql:5.7
    container_name: mysql
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
    - 3307:3306
