name: spring-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        volumes:
          # - /db/my.cnf:/etc/mysql/conf.d/my.cnf
          - /db/my.cnf:/etc/mysql/conf.d
          - /db/test.cnf:/etc/mysql/
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
    - uses: actions/checkout@v1
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      